server:
  port: 8090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jointstack
    username: postgres
    password: merlin79
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true